### ISSUE TITLE
Is this board available somewhere?

### ISSUE THREAD

**Issue by kategray** [cypresssemiconductorco/TARGET_CY8CPROTO-064B0S3#1]
I have an application I'd like to move over from the PSoC 5, and it looks like the CY8CPROTO-064B0S3 would be perfect for prototyping.

Is it available anywhere?

**Comment by rmbk19** [comment]
Hi @kategray, 

Thank you for your interest in Cypress, an Infineon Technologies Company, products!
Unfortunately, the Kit is not released yet as of this moment and is expected to be released in Q1 2021. 

Regards, 
Rakshith

**Comment by kategray** [comment]
Just noticed another update to this repository, and wanted to circle back.  Has any information on release schedules been disclosed publicly?

**Comment by rmbk19** [comment]
Hi @kategray, 

The production of the CY8CPROTO-064B0S3 devices has been delayed due to the current pandemic situation. The devices are expected to be released within this quarter.

Regards, 
Rakshith
